INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (1, '001', '0', 'Banco do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (2, '003', '4902979', 'BANCO DA AMAZONIA S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (3, '004', '7237373', 'Banco do Nordeste do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (4, '004', '33657248', 'BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (5, '010', '81723108', 'CREDICOAMO CREDITO RURAL COOPERATIVA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (6, '011', '61809182', 'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (7, '012', '4866275', 'Banco Inbursa S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (8, '014', '9274232', 'STATE STREET BRASIL S.A. - BANCO COMERCIAL');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (9, '015', '2819125', 'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (10, '015', '4715685', 'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (11, '016', '42272526', 'BNY Mellon Banco S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (12, '016', '57839805', 'Banco Tricury S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (13, '021', '28127603', 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (14, '024', '10866788', 'Banco Bandepe S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (15, '025', '3323840', 'Banco Alfa S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (16, '029', '33885724', 'Banco Itaú Consignado S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (17, '033', '90400888', 'BANCO SANTANDER (BRASIL) S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (18, '036', '6271464', 'Banco Bradesco BBI S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (19, '037', '4913711', 'Banco do Estado do Pará S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (20, '040', '3609817', 'Banco Cargill S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (21, '041', '92702067', 'Banco do Estado do Rio Grande do Sul S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (22, '047', '13009717', 'Banco do Estado de Sergipe S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (23, '060', '4913129', 'Confidence Corretora de Câmbio S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (24, '062', '3012230', 'Hipercard Banco Múltiplo S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (25, '063', '4184779', 'Banco Bradescard S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (26, '064', '4332281', 'GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (27, '065', '48795256', 'Banco AndBank (Brasil) S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (28, '066', '2801938', 'BANCO MORGAN STANLEY S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (29, '070', '208', 'BRB - BANCO DE BRASILIA S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (30, '074', '3017677', 'Banco J. Safra S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (31, '075', '3532415', 'Banco ABN Amro S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (32, '076', '7656500', 'Banco KDB do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (33, '077', '416968', 'Banco Inter S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (34, '078', '34111187', 'Haitong Banco de Investimento do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (35, '079', '9516419', 'Banco Original do Agronegócio S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (36, '080', '73622748', 'B&T CORRETORA DE CAMBIO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (37, '081', '10264663', 'BancoSeguro S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (38, '082', '7679404', 'BANCO TOPÁZIO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (39, '083', '10690848', 'Banco da China Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (40, '084', '2398976', 'UNIPRIME DO BRASIL - COOPERATIVA DE CRéDITO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (41, '085', '5463212', 'Cooperativa Central de Crédito - Ailos');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (42, '088', '11476673', 'BANCO RANDON S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (43, '089', '62109566', 'CREDISAN COOPERATIVA DE CRÉDITO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (44, '092', '12865507', 'BRK S.A. Crédito, Financiamento e Investimento');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (45, '093', '7945233', 'PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (46, '094', '11758741', 'Banco Finaxis S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (47, '095', '11703662', 'Travelex Banco de Câmbio S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (48, '096', '997185', 'Banco B3 S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (49, '097', '4632856', 'Credisis - Central de Cooperativas de Crédito Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (50, '098', '78157146', 'Credialiança Cooperativa de Crédito Rural');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (51, '099', '3046391', 'UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (52, '100', '806535', 'Planner Corretora de Valores S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (53, '101', '62287735', 'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (54, '102', '2332886', 'XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (55, '104', '360305', 'CAIXA ECONOMICA FEDERAL');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (56, '105', '7652226', 'Lecca Crédito, Financiamento e Investimento S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (57, '107', '15114366', 'Banco Bocom BBM S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (58, '108', '1800019', 'PORTOCRED S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (59, '111', '36113876', 'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (60, '113', '61723847', 'MAGLIANO S.A. CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (61, '114', '5790149', 'Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (62, '117', '92856905', 'ADVANCED CORRETORA DE CÂMBIO LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (63, '119', '13720915', 'Banco Western Union do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (64, '120', '33603457', 'BANCO RODOBENS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (65, '121', '10664513', 'Banco Agibank S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (66, '122', '33147315', 'Banco Bradesco BERJ S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (67, '124', '15357060', 'Banco Woori Bank do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (68, '125', '45246410', 'BANCO GENIAL S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (69, '126', '13220493', 'BR Partners Banco de Investimento S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (70, '127', '9512542', 'Codepe Corretora de Valores e Câmbio S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (71, '128', '19307785', 'MS Bank S.A. Banco de Câmbio');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (72, '129', '18520834', 'UBS Brasil Banco de Investimento S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (73, '130', '9313766', 'CARUANA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (74, '131', '61747085', 'TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (75, '132', '17453575', 'ICBC do Brasil Banco Múltiplo S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (76, '133', '10398952', 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (77, '134', '33862244', 'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (78, '136', '315557', 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASI');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (79, '138', '10853017', 'Get Money Corretora de Câmbio S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (80, '139', '55230916', 'Intesa Sanpaolo Brasil S.A. - Banco Múltiplo');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (81, '140', '62169875', 'NU INVEST CORRETORA DE VALORES S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (82, '142', '16944141', 'Broker Brasil Corretora de Câmbio Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (83, '143', '2992317', 'Treviso Corretora de Câmbio S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (84, '144', '13059145', 'BEXS BANCO DE CÂMBIO S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (85, '145', '50579044', 'LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (86, '146', '24074692', 'GUITTA CORRETORA DE CAMBIO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (87, '149', '15581638', 'Facta Financeira S.A. - Crédito Financiamento e Investimento');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (88, '157', '9105360', 'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (89, '159', '5442029', 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (90, '163', '23522214', 'Commerzbank Brasil S.A. - Banco Múltiplo');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (91, '173', '13486793', 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (92, '174', '43180355', 'PEFISA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (93, '177', '65913436', 'Guide Investimentos S.A. Corretora de Valores');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (94, '180', '2685483', 'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (95, '183', '9210106', 'SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (96, '184', '17298092', 'Banco Itaú BBA S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (97, '188', '33775974', 'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (98, '189', '7512441', 'HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (99, '190', '3973814', 'SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (100, '191', '4257795', 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (101, '194', '20155248', 'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (102, '195', '7799277', 'VALOR SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (103, '196', '32648370', 'FAIR CORRETORA DE CAMBIO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (104, '197', '16501555', 'Stone Pagamentos S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (105, '208', '30306294', 'Banco BTG Pactual S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (106, '212', '92894922', 'Banco Original S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (107, '213', '54403563', 'Banco Arbi S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (108, '217', '91884981', 'Banco John Deere S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (109, '218', '71027866', 'Banco BS2 S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (110, '222', '75647891', 'BANCO CRÉDIT AGRICOLE BRASIL S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (111, '224', '58616418', 'Banco Fibra S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (112, '233', '62421979', 'Banco Cifra S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (113, '237', '60746948', 'Banco Bradesco S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (114, '241', '31597552', 'BANCO CLASSICO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (115, '243', '33923798', 'BANCO MASTER S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (116, '246', '28195667', 'Banco ABC Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (117, '249', '61182408', 'Banco Investcred Unibanco S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (118, '250', '50585090', 'BCV - BANCO DE CRÉDITO E VAREJO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (119, '253', '52937216', 'Bexs Corretora de Câmbio S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (120, '254', '14388334', 'PARANÁ BANCO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (121, '259', '8609934', 'MONEYCORP BANCO DE CÂMBIO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (122, '260', '18236120', 'NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (123, '265', '33644196', 'Banco Fator S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (124, '266', '33132044', 'BANCO CEDULA S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (125, '268', '14511781', 'BARI COMPANHIA HIPOTECÁRIA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (126, '269', '53518684', 'BANCO HSBC S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (127, '270', '61444949', 'Sagitur Corretora de Câmbio Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (128, '271', '27842177', 'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (129, '272', '250699', 'AGK CORRETORA DE CAMBIO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (130, '273', '8253539', 'Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (131, '274', '11581339', 'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (132, '276', '11970623', 'BANCO SENFF S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (133, '278', '27652684', 'Genial Investimentos Corretora de Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (134, '279', '26563270', 'COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (135, '280', '23862762', 'WILL FINANCEIRA S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (136, '281', '76461557', 'Cooperativa de Crédito Rural Coopavel');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (137, '283', '89960090', 'RB INVESTIMENTOS DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LIMITADA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (138, '285', '71677850', 'Frente Corretora de Câmbio Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (139, '286', '7853842', 'COOPERATIVA DE CRÉDITO RURAL DE OURO SULCREDI/OURO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (140, '288', '62237649', 'CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (141, '289', '94968518', 'DECYSEO CORRETORA DE CAMBIO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (142, '290', '8561701', 'Pagseguro Internet S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (143, '292', '28650236', 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (144, '293', '71590442', 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (145, '296', '4062902', 'VISION S.A. CORRETORA DE CAMBIO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (146, '298', '17772370', 'Vip\'s Corretora de Câmbio Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (147, '299', '4814563', 'BANCO SOROCRED S.A. - BANCO MÚLTIPLO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (148, '300', '33042151', 'Banco de la Nacion Argentina');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (149, '301', '13370835', 'BPP Instituição de Pagamento S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (150, '306', '40303299', 'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (151, '307', '3751794', 'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (152, '309', '14190547', 'CAMBIONET CORRETORA DE CÂMBIO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (153, '310', '22610500', 'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (154, '311', '76641497', 'DOURADA CORRETORA DE CÂMBIO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (155, '312', '7693858', 'HSCM - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LT');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (156, '313', '16927221', 'AMAZÔNIA CORRETORA DE CÂMBIO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (157, '315', '3502968', 'PI Distribuidora de Títulos e Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (158, '318', '61186680', 'Banco BMG S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (159, '319', '11495073', 'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (160, '320', '7450604', 'China Construction Bank (Brasil) Banco Múltiplo S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (161, '321', '18188384', 'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (162, '322', '1073966', 'Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (163, '323', '10573521', 'MERCADOPAGO.COM REPRESENTACOES LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (164, '324', '21332862', 'CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (165, '325', '13293225', 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (166, '326', '3311443', 'PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (167, '328', '5841967', 'COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FABRICANTES DE CALÇADOS DE SAPIRANGA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (168, '329', '32402502', 'QI Sociedade de Crédito Direto S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (169, '330', '556603', 'BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (170, '331', '13673855', 'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (171, '332', '13140088', 'Acesso Soluções de Pagamento S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (172, '335', '27098060', 'Banco Digio S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (173, '336', '31872495', 'Banco C6 S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (174, '340', '9554480', 'Super Pagamentos e Administração de Meios Eletrônicos S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (175, '341', '60701190', 'ITAÚ UNIBANCO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (176, '342', '32997490', 'Creditas Sociedade de Crédito Direto S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (177, '343', '24537861', 'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (178, '348', '33264668', 'Banco XP S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (179, '349', '27214112', 'AL5 S.A. CRÉDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (180, '350', '1330387', 'COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA DO CE');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (181, '352', '29162769', 'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (182, '354', '52904364', 'NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (183, '355', '34335592', 'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (184, '358', '9464032', 'MIDWAY S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (185, '359', '5351887', 'ZEMA CRÉDITO, FINANCIAMENTO E INVESTIMENTO S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (186, '360', '2276653', 'TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (187, '362', '1027058', 'CIELO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (188, '363', '62285390', 'SINGULARE CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (189, '364', '9089356', 'GERENCIANET S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (190, '365', '68757681', 'SIMPAUL CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (191, '366', '61533584', 'BANCO SOCIETE GENERALE BRASIL S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (192, '367', '34711571', 'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (193, '368', '8357240', 'Banco CSF S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (194, '370', '61088183', 'Banco Mizuho do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (195, '371', '92875780', 'WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (196, '373', '35977097', 'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (197, '374', '27351731', 'REALIZE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (198, '376', '33172537', 'BANCO J.P. MORGAN S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (199, '377', '17826860', 'BMS SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (200, '378', '1852137', 'BBC LEASING S.A. - ARRENDAMENTO MERCANTIL');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (201, '379', '1658426', 'COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DE FUNCIONÁRIOS DE INSTITU');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (202, '380', '22896431', 'PICPAY INSTITUIçãO DE PAGAMENTO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (203, '381', '60814191', 'BANCO MERCEDES-BENZ DO BRASIL S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (204, '382', '4307598', 'FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE L');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (205, '383', '21018182', 'EBANX INSTITUICAO DE PAGAMENTOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (206, '384', '11165756', 'GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (207, '386', '30680829', 'NU FINANCEIRA S.A. - Sociedade de Crédito, Financiamento e Investimento');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (208, '387', '3215790', 'Banco Toyota do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (209, '389', '17184037', 'Banco Mercantil do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (210, '390', '59274605', 'BANCO GM S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (211, '391', '8240446', 'COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (212, '393', '59109165', 'Banco Volkswagen S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (213, '394', '7207996', 'Banco Bradesco Financiamentos S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (214, '395', '8673569', 'F.D\'GOLD - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (215, '396', '13884775', 'HUB PAGAMENTOS S.A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (216, '397', '34088029', 'LISTO SOCIEDADE DE CREDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (217, '398', '31749596', 'IDEAL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (218, '399', '1701201', 'Kirton Bank S.A. - Banco Múltiplo');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (219, '400', '5491616', 'COOPERATIVA DE CRÉDITO, POUPANÇA E SERVIÇOS FINANCEIROS DO CENTRO OESTE - CREDIT');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (220, '401', '15111975', 'IUGU INSTITUIÇÃO DE PAGAMENTO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (221, '402', '36947229', 'COBUCCIO SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (222, '403', '37880206', 'CORA SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (223, '404', '37241230', 'SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (224, '406', '37715993', 'ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (225, '407', '329598', 'ÍNDIGO INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (226, '408', '36586946', 'BONUSPAGO SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (227, '410', '5684234', 'PLANNER SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (228, '411', '5192316', 'Via Certa Financiadora S.A. - Crédito, Financiamento e Investimentos');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (229, '412', '15173776', 'BANCO CAPITAL S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (230, '413', '1858774', 'BANCO BV S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (231, '414', '37526080', 'WORK SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (232, '416', '19324634', 'LAMARA SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (233, '418', '37414009', 'ZIPDIN SOLUÇÕES DIGITAIS SOCIEDADE DE CRÉDITO DIRETO S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (234, '419', '38129006', 'NUMBRS SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (235, '421', '39343350', 'LAR COOPERATIVA DE CRÉDITO - LAR CREDI');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (236, '422', '58160789', 'Banco Safra S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (237, '423', '460065', 'COLUNA S/A DISTRIBUIDORA DE TITULOS E VALORES MOBILIÁRIOS');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (238, '425', '3881423', 'SOCINAL S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (239, '426', '11285104', 'Biorc Financeira - Crédito, Financiamento e Investimento S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (240, '427', '27302181', 'COOPERATIVA DE CREDITO DOS SERVIDORES DA UNIVERSIDADE FEDERAL DO ESPIRITO SANTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (241, '428', '39664698', 'CRED-SYSTEM SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (242, '429', '5676026', 'Crediare S.A. - Crédito, financiamento e investimento');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (243, '430', '204963', 'COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (244, '433', '44077014', 'BR-CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (245, '435', '38224857', 'DELCRED SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (246, '438', '67030395', 'PLANNER TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (247, '439', '16695922', 'ID CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (248, '440', '82096447', 'CREDIBRF - COOPERATIVA DE CRÉDITO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (249, '442', '87963450', 'MAGNETIS - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (250, '443', '39416705', 'CREDIHOME SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (251, '444', '40654622', 'TRINUS SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (252, '445', '35551187', 'PLANTAE S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (253, '447', '12392983', 'MIRAE ASSET WEALTH MANAGEMENT (BRAZIL) CORRETORA DE CÂMBIO, TÍTULOS E VALORES MO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (254, '448', '39669186', 'HEMERA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (255, '449', '37555231', 'DMCARD SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (256, '450', '13203354', 'FITBANK PAGAMENTOS ELETRONICOS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (257, '452', '39676772', 'CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (258, '454', '41592532', 'MÉRITO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (259, '456', '60498557', 'Banco MUFG Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (260, '457', '39587424', 'UY3 SOCIEDADE DE CRÉDITO DIRETO S/A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (261, '458', '7253654', 'HEDGE INVESTMENTS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (262, '459', '4546162', 'COOPERATIVA DE CRÉDITO MÚTUO DE SERVIDORES PÚBLICOS DO ESTADO DE SÃO PAULO - CRE');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (263, '461', '19540550', 'ASAAS GESTÃO FINANCEIRA INSTITUIÇÃO DE PAGAMENTO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (264, '462', '39908427', 'STARK SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (265, '464', '60518222', 'Banco Sumitomo Mitsui Brasileiro S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (266, '465', '40083667', 'CAPITAL CONSIG SOCIEDADE DE CRÉDITO DIRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (267, '467', '33886862', 'MASTER S/A CORRETORA DE CâMBIO, TíTULOS E VALORES MOBILIáRIOS');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (268, '473', '33466988', 'Banco Caixa Geral - Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (269, '477', '33042953', 'Citibank N.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (270, '479', '60394079', 'Banco ItauBank S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (271, '487', '62331228', 'DEUTSCHE BANK S.A. - BANCO ALEMAO');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (272, '488', '46518205', 'JPMorgan Chase Bank, National Association');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (273, '492', '49336860', 'ING Bank N.V.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (274, '495', '44189447', 'Banco de La Provincia de Buenos Aires');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (275, '505', '32062580', 'Banco Credit Suisse (Brasil) S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (276, '545', '17352220', 'SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (277, '600', '59118133', 'Banco Luso Brasileiro S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (278, '604', '31895683', 'Banco Industrial do Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (279, '610', '78626983', 'Banco VR S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (280, '611', '61820817', 'Banco Paulista S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (281, '612', '31880826', 'Banco Guanabara S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (282, '613', '60850229', 'Omni Banco S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (283, '623', '59285411', 'Banco Pan S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (284, '626', '61348538', 'BANCO C6 CONSIGNADO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (285, '630', '58497702', 'BANCO LETSBANK S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (286, '633', '68900810', 'Banco Rendimento S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (287, '634', '17351180', 'BANCO TRIANGULO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (288, '637', '60889128', 'BANCO SOFISA S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (289, '643', '62144175', 'Banco Pine S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (290, '652', '60872504', 'Itaú Unibanco Holding S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (291, '653', '61024352', 'BANCO VOITER S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (292, '654', '92874270', 'BANCO DIGIMAIS S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (293, '655', '59588111', 'Banco Votorantim S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (294, '69', '61033106', 'Banco Crefisa S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (295, '707', '62232889', 'Banco Daycoval S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (296, '712', '78632767', 'Banco Ourinvest S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (297, '720', '80271455', 'BANCO RNX S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (298, '739', '558456', 'Banco Cetelem S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (299, '741', '517645', 'BANCO RIBEIRAO PRETO S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (300, '743', '795423', 'Banco Semear S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (301, '745', '33479023', 'Banco Citibank S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (302, '746', '30723886', 'Banco Modal S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (303, '747', '1023570', 'Banco Rabobank International Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (304, '748', '1181521', 'BANCO COOPERATIVO SICREDI S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (305, '751', '29030467', 'Scotiabank Brasil S.A. Banco Múltiplo');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (306, '752', '1522368', 'Banco BNP Paribas Brasil S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (307, '753', '74828799', 'Novo Banco Continental S.A. - Banco Múltiplo');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (308, '754', '76543115', 'Banco Sistema S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (309, '755', '62073200', 'Bank of America Merrill Lynch Banco Múltiplo S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (310, '756', '2038232', 'BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (311, '757', '2318507', 'BANCO KEB HANA DO BRASIL S.A.');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (312, '99901', '38121', 'Banco Central do Brasil - Selic');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (313, '99902', '38166', 'Banco Central do Brasil');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (314, '99903', '394460', 'Secretaria do Tesouro Nacional - STN');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (315, '99904', '2992335', 'Câmara Interbancária de Pagamentos - CIP - LDL');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (316, '99905', '4391007', 'Câmara Interbancária de Pagamentos');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (317, '99906', '28719664', 'Sistema do Balcão B3');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (318, '99907', '29011780', 'Câmara Interbancária de Pagamentos - CIP C3');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (319, '99908', '54641030', 'Câmara B3');
INSERT INTO `bancos` (`id`, `compe`, `ispb`, `razao_social`) VALUES (320, '99909', '60934221', 'Câmara de Câmbio B3');
